@startuml

interface Call extends Cloneable {
Request request();
Response execute() throws IOException;
void enqueue(Callback responseCallback);
void cancel();
boolean isExecuted();
boolean isCanceled();
Call clone();

}
interface Factory {
    Call newCall(Request request);
}

Factory ..> Call

Call <|-- RealCall
class RealCall{
public void enqueue(Callback responseCallback)
Response getResponseWithInterceptorChain()


}
@enduml